# Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-markdown-memo
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 523.0.1
        run.googleapis.com/cloudsql-instances: flask-memo:asia-northeast1:flask-memo-db
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/flask-markdown-memo
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://username:password@host:5432/database"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
